# Generated by Django 4.0.6 on 2022-12-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_list_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
