# Generated by Django 4.0.6 on 2022-12-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='List',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.list'),
        ),
    ]
