# Generated by Django 4.0.6 on 2022-12-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_alter_list_user_alter_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='List',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.list'),
        ),
    ]
